name: flutter_deriv_packages
repository: https://github.com/deriv-com/flutter-deriv-packages.git

ignore:
  # e.g. ignore example apps
  - "packages/**/example"

packages:
  - packages/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    workspaceChangelog: true
    updateGitTagRefs: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  analyze:
    name: Flutter Analyze
    description: Run flutter analyze for all packages.
    ## Only fail if there are errors or warnings and not on infos.
    run: |
      if flutter analyze 2>&1 | grep -q -E 'error:|warning:'; 
          then exit 1
          else exit 0
      fi
    exec:
      concurrency: 1
      failFast: true

  test:
    name: Flutter Test
    description: Run flutter test for all packages.
    run: flutter test --coverage
    exec:
      concurrency: 6
      failFast: true
    packageFilters:
      dirExists:
        - test
      ignore:
        # Ignore until we have a proper test.
        - "deriv_feature_flag"
        - "deriv_auth"
